import { defineSlotRecipe } from "@pandacss/dev";

/**
 * ColorPicker slot recipe.
 *
 * data-scope="colorPicker" on every part; data-part values match the keys below.
 */
const slots = [
	"root",
	"label",
	"control",
	"content",
	"area",
	"areaBackground",
	"areaThumb",
	"channelSlider",
	"channelSliderLabel",
	"channelSliderTrack",
	"channelSliderThumb",
	"channelSliderValueText",
	"swatchGroup",
	"swatch",
	"swatchIndicator",
	"swatchTrigger",
	"transparencyGrid",
	"trigger",
	"positioner",
	"formatSelect",
	"formatTrigger",
	"valueSwatch",
	"valueText",
	"view",
	"channelInput",
	"eyeDropperTrigger",
] as const;

export const colorPicker = defineSlotRecipe({
	className: "color-picker",
	slots,
	base: {
		root: {
			display: "flex",
			flexDirection: "column",
			gap: "1.5",
			minWidth: "0",
			// The trigger-mode Positioner is `position: absolute` (see
			// color-picker-primitive.tsx), which resolves relative to the
			// nearest positioned ancestor. Without this, that's whatever
			// happens to wrap the picker (e.g. a Card, which is `position:
			// relative` for its own image-clipping reasons) instead of the
			// picker itself — same fix Popover applies via its own
			// `data-overlay-root` wrapper.
			position: "relative",
		},
		label: {
			color: "fg.default",
			fontWeight: "medium",
			textStyle: "sm",
		},
		control: {
			display: "flex",
			flexDirection: "row",
			gap: "2",
			alignItems: "stretch",
		},
		content: {
			background: "gray.surface.bg",
			borderRadius: "l3",
			boxShadow: "lg",
			display: "flex",
			flexDirection: "column",
			gap: "3",
			maxWidth: "sm",
			p: "4",
			zIndex: "dropdown",
			_hidden: { display: "none" },
		},
		area: {
			height: "36",
			minWidth: "0",
			flex: "1",
			borderRadius: "l2",
			overflow: "hidden",
			position: "relative",
			touchAction: "none",
			cursor: "crosshair",
			userSelect: "none",
			outline: "none",
			_focusVisible: {
				ring: "2px",
				ringColor: "colorPalette.solid",
				ringOffset: "2px",
				ringOffsetColor: "bg",
			},
		},
		areaBackground: {
			position: "absolute",
			inset: "0",
			height: "full",
			width: "full",
			// Base hue color is injected inline by JS. The two overlays below
			// produce the classic saturation (horizontal) + value (vertical) square.
			backgroundImage:
				"linear-gradient(to top, rgba(0,0,0,1), rgba(0,0,0,0)), linear-gradient(to right, rgba(255,255,255,1), rgba(255,255,255,0))",
		},
		areaThumb: {
			position: "absolute",
			borderRadius: "full",
			height: "2.5",
			width: "2.5",
			boxShadow: "white 0px 0px 0px 2px, black 0px 0px 2px 1px",
			outline: "none",
			translate: "-50% -50%",
			pointerEvents: "none",
		},
		channelSlider: {
			borderRadius: "l2",
			display: "flex",
			flexDirection: "column",
			gap: "1",
			minWidth: "0",
		},
		channelSliderLabel: {
			color: "fg.muted",
			textStyle: "xs",
			fontWeight: "medium",
		},
		channelSliderTrack: {
			position: "relative",
			height: "3",
			borderRadius: "l2",
			overflow: "hidden",
			touchAction: "none",
			cursor: "pointer",
			userSelect: "none",
			outline: "none",
			_focusVisible: {
				ring: "2px",
				ringColor: "colorPalette.solid",
				ringOffset: "2px",
				ringOffsetColor: "bg",
			},
		},
		channelSliderThumb: {
			position: "absolute",
			top: "50%",
			borderRadius: "full",
			height: "2.5",
			width: "2.5",
			boxShadow: "white 0px 0px 0px 2px, black 0px 0px 2px 1px",
			transform: "translate(-50%, -50%)",
			outline: "none",
			pointerEvents: "none",
		},
		channelSliderValueText: {
			color: "fg.muted",
			textStyle: "xs",
			fontVariantNumeric: "tabular-nums",
		},
		swatchGroup: {
			display: "grid",
			gridTemplateColumns: "repeat(7, 1fr)",
			gap: "1.5",
		},
		swatch: {
			height: "6",
			width: "6",
			borderRadius: "l2",
			position: "relative",
			cursor: "pointer",
			outline: "none",
			_focusVisible: {
				ring: "2px",
				ringColor: "colorPalette.solid",
				ringOffset: "2px",
				ringOffsetColor: "bg",
			},
		},
		swatchIndicator: {
			borderRadius: "l2",
			boxShadow: "0 0 0 2px var(--colors-bg-default)",
			position: "absolute",
			inset: "0",
			pointerEvents: "none",
		},
		swatchTrigger: {
			appearance: "none",
			border: "none",
			p: "0",
			cursor: "pointer",
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			borderRadius: "l2",
			height: "9",
			width: "9",
			position: "relative",
			outline: "none",
			_focusVisible: {
				ring: "2px",
				ringColor: "colorPalette.solid",
				ringOffset: "2px",
				ringOffsetColor: "bg",
			},
		},
		transparencyGrid: {
			borderRadius: "l2",
			backgroundColor: "#fff",
			backgroundImage:
				"linear-gradient(45deg, var(--colors-border-default) 25%, transparent 25%), linear-gradient(-45deg, var(--colors-border-default) 25%, transparent 25%), linear-gradient(45deg, transparent 75%, var(--colors-border-default) 75%), linear-gradient(-45deg, transparent 75%, var(--colors-border-default) 75%)",
			backgroundSize: "8px 8px",
			backgroundPosition: "0 0, 0 4px, 4px -4px, -4px 0",
		},
		trigger: {
			display: "inline-flex",
		},
		positioner: {
			position: "relative",
			display: "inline-flex",
		},
		formatSelect: {
			appearance: "none",
			borderWidth: "1px",
			borderColor: "border",
			borderRadius: "l2",
			bg: "gray.surface.bg",
			color: "fg.default",
			textStyle: "sm",
			px: "2",
			h: "8",
			cursor: "pointer",
		},
		formatTrigger: {
			appearance: "none",
			borderWidth: "1px",
			borderColor: "border",
			borderRadius: "l2",
			bg: "gray.surface.bg",
			color: "fg.default",
			textStyle: "xs",
			px: "2",
			h: "8",
			cursor: "pointer",
		},
		valueSwatch: {
			borderRadius: "l2",
			height: "8",
			width: "8",
			boxShadow:
				"0 0 0 1px var(--colors-border-emphasized), 0 0 0 2px var(--colors-bg-default) inset",
			position: "relative",
			flexShrink: "0",
		},
		valueText: {
			color: "fg.default",
			textStyle: "sm",
			fontVariantNumeric: "tabular-nums",
		},
		view: {
			display: "flex",
			flexDirection: "column",
			gap: "1.5",
			minWidth: "0",
		},
		channelInput: {
			appearance: "none",
			borderWidth: "1px",
			borderColor: "border",
			borderRadius: "l2",
			bg: "bg.default",
			color: "fg.default",
			textStyle: "sm",
			px: "2",
			h: "8",
			width: "full",
			_focusVisible: {
				borderColor: "colorPalette.solid",
				boxShadow: "0 0 0 1px var(--colors-color-palette-solid)",
			},
			_disabled: {
				opacity: "0.5",
				cursor: "not-allowed",
			},
		},
		eyeDropperTrigger: {
			appearance: "none",
			borderWidth: "1px",
			borderColor: "border",
			borderRadius: "l2",
			bg: "gray.surface.bg",
			color: "fg.default",
			h: "8",
			w: "8",
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			cursor: "pointer",
			_disabled: {
				opacity: "0.5",
				cursor: "not-allowed",
			},
		},
	},
	defaultVariants: {
		size: "md",
	},
	variants: {
		size: {
			sm: {
				root: { gap: "1" },
				area: { height: "28" },
				swatchGroup: { gap: "1" },
				swatch: { height: "5", width: "5" },
				valueSwatch: { height: "7", width: "7" },
			},
			md: {},
			lg: {
				root: { gap: "2" },
				area: { height: "44" },
				swatchGroup: { gap: "2" },
				swatch: { height: "7", width: "7" },
				valueSwatch: { height: "9", width: "9" },
			},
		},
	},
});
