import { defineSlotRecipe } from "@pandacss/dev";
import { input } from "./input";

export const datePicker = defineSlotRecipe({
	className: "date-picker",
	slots: [
		"clearTrigger",
		"content",
		"control",
		"input",
		"label",
		"monthSelect",
		"nextTrigger",
		"positioner",
		"presetTrigger",
		"prevTrigger",
		"rangeText",
		"root",
		"table",
		"tableBody",
		"tableCell",
		"tableCellTrigger",
		"tableHead",
		"tableHeader",
		"tableRow",
		"trigger",
		"view",
		"viewControl",
		"weekNumber",
		"viewTrigger",
		"yearSelect",
		"valueText",
	],
	base: {
		root: {
			display: "flex",
			flexDirection: "column",
			gap: "1.5",
		},
		label: {
			textStyle: "label",
		},
		control: {
			alignItems: "center",
			display: "flex",
			flexDirection: "row",
			gap: "2",
		},
		input: {
			...input.base,
			...input.variants.variant.outline,
			...input.variants.size.md,
		},
		trigger: {
			alignItems: "center",
			borderColor: "gray.outline.border",
			borderRadius: "l2",
			borderWidth: "1px",
			color: "fg.muted",
			cursor: "pointer",
			display: "inline-flex",
			flexShrink: "0",
			height: "10",
			justifyContent: "center",
			transition: "colors",
			width: "10",
			focusVisibleRing: "outside",
			_hover: {
				background: "gray.plain.bg.hover",
				color: "fg.default",
			},
			_disabled: {
				layerStyle: "disabled",
			},
		},
		clearTrigger: {
			alignItems: "center",
			borderRadius: "l2",
			color: "fg.muted",
			cursor: "pointer",
			display: "inline-flex",
			flexShrink: "0",
			height: "10",
			justifyContent: "center",
			transition: "colors",
			width: "10",
			focusVisibleRing: "outside",
			_hover: {
				background: "gray.plain.bg.hover",
				color: "fg.default",
			},
			_disabled: {
				layerStyle: "disabled",
			},
		},
		positioner: {
			zIndex: "dropdown",
		},
	content: {
		background: "gray.surface.bg",
		borderColor: "gray.surface.border",
		borderRadius: "l3",
		borderWidth: "1px",
		boxShadow: "lg",
		display: "flex",
		flexDirection: "column",
		gap: "3",
		maxWidth: "100%",
		outline: "none",
		p: "4",
		width: "344px",
		zIndex: "dropdown",
		// The content carries `data-state="open" | "closed"`. Use explicit
		// attribute selectors — Panda's `_open`/`_closed` conditions target
		// `[data-open]`/`[data-closed]`, which this component never sets, so
		// the open animation would otherwise be a silent no-op.
		'&[data-state="open"]': {
			animation: "fade-in 0.2s ease-out",
		},
		'&[data-state="closed"]': {
			animation: "fade-out 0.15s ease-in",
		},
	},
		view: {
			display: "flex",
			flexDirection: "column",
			gap: "3",
			_hidden: {
				display: "none",
			},
		},
		viewControl: {
			alignItems: "center",
			display: "flex",
			gap: "2",
			justifyContent: "space-between",
		},
		prevTrigger: {
			alignItems: "center",
			borderRadius: "l2",
			color: "fg.muted",
			cursor: "pointer",
			display: "inline-flex",
			flexShrink: "0",
			height: "9",
			justifyContent: "center",
			transition: "colors",
			width: "9",
			focusVisibleRing: "inside",
			_hover: {
				background: "gray.plain.bg.hover",
				color: "fg.default",
			},
			_disabled: {
				layerStyle: "disabled",
			},
		},
		nextTrigger: {
			alignItems: "center",
			borderRadius: "l2",
			color: "fg.muted",
			cursor: "pointer",
			display: "inline-flex",
			flexShrink: "0",
			height: "9",
			justifyContent: "center",
			transition: "colors",
			width: "9",
			focusVisibleRing: "inside",
			_hover: {
				background: "gray.plain.bg.hover",
				color: "fg.default",
			},
			_disabled: {
				layerStyle: "disabled",
			},
		},
		viewTrigger: {
			alignItems: "center",
			borderRadius: "l2",
			color: "fg.default",
			cursor: "pointer",
			display: "inline-flex",
			fontWeight: "semibold",
			gap: "1",
			height: "9",
			justifyContent: "center",
			px: "2.5",
			textStyle: "sm",
			transition: "colors",
			focusVisibleRing: "inside",
			_hover: {
				background: "gray.plain.bg.hover",
			},
		},
		rangeText: {
			fontWeight: "semibold",
			textStyle: "sm",
		},
		table: {
			borderCollapse: "separate",
			borderSpacing: "1",
			m: "-1",
			tableLayout: "fixed",
			width: "full",
		},
		tableHeader: {
			color: "fg.muted",
			fontWeight: "medium",
			height: "10",
			textStyle: "sm",
		},
		tableCell: {
			p: "0",
			textAlign: "center",
		},
		tableCellTrigger: {
			alignItems: "center",
			borderRadius: "l2",
			color: "fg.default",
			cursor: "pointer",
			display: "inline-flex",
			fontVariantNumeric: "tabular-nums",
			height: "10",
			justifyContent: "center",
			position: "relative",
			textStyle: "sm",
			transition: "colors",
			width: "full",
			focusVisibleRing: "inside",
			_hover: {
				background: "gray.plain.bg.hover",
			},
			"&[data-outside-range]": {
				color: "fg.subtle",
			},
			"&[data-in-range]:not([data-selected])": {
				background: "colorPalette.subtle.bg",
				borderRadius: "0",
				color: "colorPalette.subtle.fg",
			},
			"&[data-range-preview]:not([data-selected])": {
				background: "colorPalette.subtle.bg",
				borderRadius: "0",
				color: "colorPalette.subtle.fg",
			},
			_today: {
				fontWeight: "semibold",
				_after: {
					background: "colorPalette.solid.bg",
					borderRadius: "full",
					bottom: "1",
					boxSize: "1",
					content: '""',
					insetStart: "50%",
					position: "absolute",
					transform: "translateX(-50%)",
				},
			},
			_selected: {
				background: "colorPalette.solid.bg",
				color: "colorPalette.solid.fg",
				fontWeight: "semibold",
				_hover: {
					background: "colorPalette.solid.bg.hover",
				},
				_after: {
					display: "none",
				},
			},
			_disabled: {
				layerStyle: "disabled",
				_hover: {
					background: "transparent",
				},
			},
		},
		weekNumber: {
			color: "fg.subtle",
			fontVariantNumeric: "tabular-nums",
			fontSize: "xs",
			height: "10",
			textAlign: "center",
		},
		monthSelect: {
			background: "transparent",
			borderColor: "gray.outline.border",
			borderRadius: "l2",
			borderWidth: "1px",
			color: "fg.default",
			cursor: "pointer",
			height: "9",
			px: "2",
			textStyle: "sm",
			focusVisibleRing: "inside",
			_disabled: {
				layerStyle: "disabled",
			},
		},
		yearSelect: {
			background: "transparent",
			borderColor: "gray.outline.border",
			borderRadius: "l2",
			borderWidth: "1px",
			color: "fg.default",
			cursor: "pointer",
			height: "9",
			px: "2",
			textStyle: "sm",
			focusVisibleRing: "inside",
			_disabled: {
				layerStyle: "disabled",
			},
		},
		presetTrigger: {
			alignItems: "center",
			background: "gray.subtle.bg",
			borderRadius: "l2",
			color: "gray.subtle.fg",
			cursor: "pointer",
			display: "inline-flex",
			fontWeight: "medium",
			height: "8",
			justifyContent: "center",
			px: "2.5",
			textStyle: "sm",
			transition: "colors",
			focusVisibleRing: "outside",
			_hover: {
				background: "gray.subtle.bg.hover",
			},
			_disabled: {
				layerStyle: "disabled",
			},
		},
		valueText: {
			color: "fg.muted",
			textStyle: "sm",
		},
	},
	defaultVariants: {
		colorPalette: "blue",
	},
	variants: {
		colorPalette: {
			blue: { root: { colorPalette: "blue" } },
			green: { root: { colorPalette: "green" } },
			red: { root: { colorPalette: "red" } },
			orange: { root: { colorPalette: "orange" } },
			gray: { root: { colorPalette: "gray" } },
			cyan: { root: { colorPalette: "cyan" } },
			amber: { root: { colorPalette: "amber" } },
			purple: { root: { colorPalette: "purple" } },
		},
	},
});
