import { defineSlotRecipe } from "@pandacss/dev";

export const fileUpload = defineSlotRecipe({
	className: "file-upload",
	slots: [
		"root",
		"label",
		"dropzone",
		"trigger",
		"item",
		"itemGroup",
		"itemName",
		"itemPreview",
		"itemPreviewImage",
		"itemSizeText",
		"itemDeleteTrigger",
		"clearTrigger",
	],
	base: {
		root: {
			alignItems: "flex-start",
			display: "flex",
			flexDirection: "column",
			width: "full",
			_disabled: {
				opacity: "0.5",
				pointerEvents: "none",
			},
		},
		label: {
			textStyle: "label",
		},
		dropzone: {
			alignItems: "center",
			background: "gray.surface.bg",
			borderRadius: "l3",
			borderStyle: "dashed",
			borderWidth: "2px",
			cursor: "pointer",
			display: "flex",
			flexDirection: "column",
			focusVisibleRing: "outside",
			justifyContent: "center",
			textAlign: "center",
			transitionDuration: "normal",
			transitionProperty: "background, border-color",
			width: "full",
			_dragging: {
				background: "gray.surface.bg.hover",
				borderStyle: "solid",
				borderColor: "colorPalette.solid.bg",
			},
			_invalid: {
				borderColor: "error",
			},
		},
		trigger: {
			alignItems: "center",
			borderRadius: "l2",
			borderWidth: "1px",
			cursor: "pointer",
			display: "inline-flex",
			focusVisibleRing: "outside",
			fontWeight: "medium",
			justifyContent: "center",
			transition: "colors",
			_hover: {
				background: "gray.surface.bg.hover",
			},
		},
		item: {
			alignItems: "start",
			animationDuration: "normal",
			animationName: "fade-in",
			background: "gray.surface.bg",
			borderRadius: "l3",
			borderWidth: "1px",
			display: "flex",
			pos: "relative",
			textAlign: "start",
			width: "full",
		},
		itemGroup: {
			display: "flex",
			alignItems: "start",
			flexDirection: "column",
			listStyle: "none",
			width: "full",
		},
		itemName: {
			color: "fg.default",
			fontWeight: "medium",
			lineClamp: "1",
			wordBreak: "break-all",
		},
		itemSizeText: {
			color: "fg.muted",
		},
		itemPreview: {
			alignItems: "center",
			color: "fg.muted",
			display: "flex",
			justifyContent: "center",
		},
		itemPreviewImage: {
			aspectRatio: "1",
			objectFit: "cover",
			maxW: "20",
			borderRadius: "l2",
		},
		itemDeleteTrigger: {
			alignItems: "center",
			borderRadius: "l1",
			color: "fg.subtle",
			cursor: "pointer",
			display: "inline-flex",
			focusVisibleRing: "outside",
			justifyContent: "center",
			_hover: {
				color: "fg.default",
			},
		},
		clearTrigger: {
			alignItems: "center",
			borderRadius: "l1",
			color: "fg.muted",
			cursor: "pointer",
			display: "inline-flex",
			focusVisibleRing: "outside",
			justifyContent: "center",
			_hover: {
				color: "fg.default",
			},
			_hidden: {
				display: "none",
			},
		},
	},
	defaultVariants: {
		size: "md",
	},
	variants: {
		size: {
			sm: {
				root: { gap: "3" },
				dropzone: {
					px: "4",
					py: "3",
					minHeight: "32",
					gap: "1",
					textStyle: "sm",
				},
				trigger: { h: "8", px: "3", textStyle: "xs", gap: "1" },
				item: { p: "3", gap: "2.5", textStyle: "xs" },
				itemGroup: { gap: "2.5" },
				itemPreview: { _icon: { boxSize: "3.5" } },
				itemDeleteTrigger: { _icon: { boxSize: "3.5" } },
				clearTrigger: { _icon: { boxSize: "3.5" } },
			},
			md: {
				root: { gap: "4" },
				dropzone: {
					px: "6",
					py: "4",
					minHeight: "40",
					gap: "1",
					textStyle: "sm",
				},
				trigger: { h: "9", px: "3.5", textStyle: "sm", gap: "2" },
				item: { p: "4", gap: "3", textStyle: "sm" },
				itemGroup: { gap: "3" },
				itemPreview: { _icon: { boxSize: "4" } },
				itemDeleteTrigger: { _icon: { boxSize: "4" } },
				clearTrigger: { _icon: { boxSize: "4" } },
			},
			lg: {
				root: { gap: "4" },
				dropzone: {
					px: "8",
					py: "6",
					minHeight: "48",
					gap: "1.5",
					textStyle: "md",
				},
				trigger: { h: "10", px: "4", textStyle: "sm", gap: "2" },
				item: { p: "4", gap: "3", textStyle: "md" },
				itemGroup: { gap: "3" },
				itemPreview: { _icon: { boxSize: "5" } },
				itemDeleteTrigger: { _icon: { boxSize: "4.5" } },
				clearTrigger: { _icon: { boxSize: "4.5" } },
			},
		},
	},
});
