import { defineSlotRecipe } from "@pandacss/dev";

export const popover = defineSlotRecipe({
	className: "popover",
	slots: [
		"anchor",
		"arrow",
		"arrowTip",
		"closeTrigger",
		"content",
		"description",
		"indicator",
		"positioner",
		"title",
		"trigger",
		"header",
		"body",
		"footer",
	],
	base: {
		content: {
			"--popover-bg": "colors.gray.surface.bg",
			"--popover-padding": "spacing.4",

			background: "var(--popover-bg)",
			borderRadius: "l3",
			borderWidth: "1px",
			borderColor: "gray.surface.border",
			boxShadow: "lg",
			display: "flex",
			flexDirection: "column",
			maxHeight: "var(--available-height)",
			overflowY: "auto",
			overscrollBehavior: "contain",
			outline: "0",
			position: "relative",
			textStyle: "sm",
			transformOrigin: "var(--transform-origin)",
			width: "xs",
			maxWidth: "calc(100vw - (2 * var(--popover-edge-gap, 1rem)))",
			zIndex: "calc(var(--z-index-popover) + var(--layer-index, 0))",
			_open: {
				animationStyle: "scale-fade-in",
				animationDuration: "fast",
			},
			_closed: {
				animationStyle: "scale-fade-out",
				animationDuration: "faster",
			},
		},
		title: {
			color: "fg.default",
			fontWeight: "medium",
			textStyle: "md",
		},
		description: {
			color: "fg.muted",
			textStyle: "sm",
		},
		closeTrigger: {
			position: "absolute",
			top: "1",
			right: "1",
		},
		header: {
			display: "flex",
			flexDirection: "column",
			pt: "var(--popover-padding)",
			px: "var(--popover-padding)",
		},
		body: {
			p: "var(--popover-padding)",
			display: "flex",
			flex: "1",
			flexDirection: "column",
			gap: "4",
		},
		footer: {
			display: "flex",
			alignItems: "center",
			justifyContent: "flex-end",
			gap: "3",
			paddingInline: "var(--popover-padding)",
			paddingBottom: "var(--popover-padding)",
		},
		arrow: {
			"--arrow-size": "sizes.3",
			"--arrow-background": "var(--popover-bg)",
			position: "absolute",
			width: "var(--arrow-size)",
			height: "var(--arrow-size)",
			zIndex: "1",
		},
		arrowTip: {
			position: "absolute",
			inset: "0",
			width: "var(--arrow-size)",
			height: "var(--arrow-size)",
			background: "var(--arrow-background)",
			transform: "rotate(45deg)",
			borderTopWidth: "0.5px",
			borderInlineStartWidth: "0.5px",
			borderColor: "border",
		},
	},
});
