import { describe, expect, it } from "bun:test";
import { parseStyleString, extractLayoutStyle } from "../block-style";
import { propsOf } from "../block-types";

describe("CMS Static CSS Generalized Bridge", () => {
	describe("parseStyleString", () => {
		it("should parse and validate standard categorical style properties", () => {
			const parsed = parseStyleString("text-align: center; font-weight: bold; text-transform: uppercase");
			expect(parsed).toEqual([
				{ type: "categorical", name: "textAlign", value: "center" },
				{ type: "categorical", name: "fontWeight", value: "bold" },
				{ type: "categorical", name: "textTransform", value: "uppercase" },
			]);
		});

		it("should parse and validate standard continuous style properties", () => {
			const parsed = parseStyleString("margin-bottom: 2rem; max-width: 42rem");
			expect(parsed).toEqual([
				{ type: "continuous", name: "marginBottom", value: "2rem" },
				{ type: "continuous", name: "maxWidth", value: "42rem" },
			]);
		});

		it("should normalize hardcoded hexes to semantic tokens", () => {
			const parsed = parseStyleString("color: #71717a; border-bottom-color: #e5e7eb");
			expect(parsed).toEqual([
				{ type: "categorical", name: "color", value: "var(--colors-fg-muted)" },
				{ type: "categorical", name: "borderBottomColor", value: "var(--colors-border)" },
			]);
		});

		it("should decompose border shorthands correctly", () => {
			const parsed = parseStyleString("border-bottom: 1px solid #e5e7eb");
			expect(parsed).toEqual([
				{ type: "continuous", name: "borderBottomWidth", value: "1px" },
				{ type: "categorical", name: "borderBottomStyle", value: "solid" },
				{ type: "categorical", name: "borderBottomColor", value: "var(--colors-border)" },
			]);
		});

		it("should silently drop unvalidated/arbitrary CSS declarations", () => {
			const parsed = parseStyleString("position: absolute; color: #71717a; invalid-prop: yes");
			expect(parsed).toEqual([
				{ type: "categorical", name: "color", value: "var(--colors-fg-muted)" },
			]);
		});
	});

	describe("propsOf and block style integration", () => {
		it("should merge parsed style properties directly into props for layout blocks", () => {
			const block = {
				blockType: "grid",
				style: "margin-bottom: 2rem; text-align: center",
				columns: 3,
			};

			const props = propsOf(block);
			expect(props.columns).toBe(3);
			expect(props.marginBottom).toBe("2rem");
			expect(props.textAlign).toBe("center");
			expect(props.style).toBeUndefined(); // raw style string is deleted
		});

		it("should generate classes and style variables for non-layout blocks", () => {
			const block = {
				blockType: "text",
				style: "color: #71717a; max-width: 42rem; margin-bottom: 2rem",
				content: "Hello World",
			};

			const props = propsOf(block);
			expect(props.content).toBe("Hello World");
			expect(props.class).toBeDefined();
			expect(props.class).toContain("c_var(--colors-fg-muted)"); // real class generated by css()
			expect(props.style).toBeDefined();
			expect(props.style).toContain("--cms-max-width: 42rem");
			expect(props.style).toContain("--cms-margin-bottom: 2rem");
		});
	});

	describe("extractLayoutStyle for layout blocks", () => {
		it("should extract combined styles into continuous variables and categorical classes", () => {
			const props = {
				columns: 3,
				marginBottom: "2rem",
				textAlign: "center",
			};

			const layoutStyle = extractLayoutStyle(props);
			expect(props.marginBottom).toBeUndefined(); // processed key is deleted
			expect(props.textAlign).toBeUndefined();     // processed key is deleted
			expect(props.columns).toBe(3);               // non-style key remains

			expect(layoutStyle.class).toBeDefined();
			expect(layoutStyle.class).toContain("ta_center"); // real class from css()
			expect(layoutStyle.style).toBeDefined();
			expect(layoutStyle.style).toContain("--cms-margin-bottom: 2rem");
		});
	});
});
